---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-training1
  labels:
    app: energy-training1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-training1
  template:
    metadata:
      labels:
        app: energy-training1
    spec:
      containers:
      - name: energy-training1
        image: docker.io/aditya2277/energy-training:latest
        ports:
        - name: protobuf-api
          containerPort: 8061
        - name: webui
          containerPort: 8062
