---
apiVersion: v1
kind: Service
metadata:
  name: energy-databroker1
spec:
  selector:
    app: energy-databroker1
  type: NodePort
  ports:
  - name: protobuf-api
    port: 8556
    targetPort: 8061
